// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// For Firebase JS SDK v7.20.0 and later, measurementId is optional
 static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCmm1HyOTu3aR9HMcWYHoXYwV1A84rPG_k",
  authDomain: "weather-app-c9193.firebaseapp.com",
  projectId: "weather-app-c9193",
  storageBucket: "weather-app-c9193.firebasestorage.app",
  messagingSenderId: "927136243088",
  appId: "1:927136243088:web:dae77bd8d878d1d3d62715",
  measurementId: "G-9K202GNLKE"
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFDRsZNZXSOmTA5kL1fSXMcAo02hH3As',
    appId: '1:927136243088:android:5ecc13b4843a9a67d62715',
    messagingSenderId: '927136243088',
    projectId: 'weather-app-c9193',
    storageBucket: 'weather-app-c9193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhy9rktggU5egESWJmu5KGaSmgSSadTrA',
    appId: '1:927136243088:ios:1af223da5b8192e5d62715',
    messagingSenderId: '927136243088',
    projectId: 'weather-app-c9193',
    storageBucket: 'weather-app-c9193.firebasestorage.app',
    iosBundleId: 'com.example.weatherApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhy9rktggU5egESWJmu5KGaSmgSSadTrA',
    appId: '1:927136243088:ios:1af223da5b8192e5d62715',
    messagingSenderId: '927136243088',
    projectId: 'weather-app-c9193',
    storageBucket: 'weather-app-c9193.firebasestorage.app',
    iosBundleId: 'com.example.weatherApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmm1HyOTu3aR9HMcWYHoXYwV1A84rPG_k',
    appId: '1:927136243088:web:6fa892c37a628e0dd62715',
    messagingSenderId: '927136243088',
    projectId: 'weather-app-c9193',
    authDomain: 'weather-app-c9193.firebaseapp.com',
    storageBucket: 'weather-app-c9193.firebasestorage.app',
    measurementId: 'G-HH7ZDPDQWF',
  );
}
